version: '3'

services:
  ubuntu-container:
    image: ubuntu:latest
    volumes:
      - ./LinuxServer:/app
    ports:
      - "7777:7777/udp"
    command: bash -c "chmod +x FinalGameServer.sh && ./app/FinalGameServer.sh"
