# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-nodejs

name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
      runs-on: ubuntu-22.04
  
      steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.1

  build_Node:

    runs-on: ubuntu-22.04

    strategy:
      matrix:
        node-version: [20.x]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4.0.2
      with:
        # Used to specify the path to a dependency file: package-lock.json, yarn.lock, etc. Supports wildcards or a list of file names for caching multiple dependencies.
        cache-dependency-path: '/WS_SESSION_COMMUNICATIONS'
        # Version Spec of the version to use. Examples: 12.x, 10.15.1, >=10.15.0.
        node-version: ${{ matrix.node-version }}
        # Used to specify a package manager for caching in the default directory. Supported values: npm, yarn, pnpm.
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
          